name: lip_sync_avatar
description: Una aplicación Flutter para sincronización labial de avatar 3D con audio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  model_viewer_plus: ^1.5.0
  just_audio: ^0.9.34
  file_picker: ^5.3.0
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_tts: ^3.7.0
  bezier: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/rive/
    - assets/avatar.glb
